blank_issues_enabled: true
contact_links:
  - name: I have a question!
    url: https://discord.com/channels/937435293294919690/1509824106734817290
  - name: I have a suggestion or idea!
    url: https://discord.com/channels/937435293294919690/1509824106734817290
  - name: Talk to us on Discord thread in Create Aeronautics Discord.
    url: https://discord.com/channels/937435293294919690/1509824106734817290
    about: Ask questions and get help.
